version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: main
  
  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: daily
    target-branch: main
    
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: daily
    target-branch: main
