### variable ###
variable "pj" {}
variable "env" {}
variable "vpc_id" {}
variable "public_subnet_c_ids" {}
variable "public_subnet_d_ids" {}
variable "acm_certificate" {}
variable "basic_user_pool_arn" {}
variable "basic_user_pool_client_back_id" {}
variable "basic_user_pool_domain" {}
