### variable ###
variable "pj" {}
variable "env" {}
variable "vpc_id" {}
variable "public_subnet_c_ids" {}
variable "public_subnet_d_ids" {}
variable "acm_certificate" {}
variable "alb_sg_id" {}
variable "frontend_ecs_blue_tg" {}
variable "frontend_ecs_green_tg" {}
variable "https_listener" {}
variable "frontend_4430_listener" {}
