CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    cognito_id VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    birthday DATE,
    description TEXT,
    logo_url VARCHAR(255),
    delete_flg BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3)
);