# name: Assign Author

# on:
#   pull_request:
#     types: [opened]

# jobs:
#   assign-author:
#     if: ${{ ! contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
#     permissions:
#       pull-requests: write
#     runs-on: ubuntu-latest
#     steps:
#       - uses: technote-space/assign-author@v1

# # 参考資料: https://qiita.com/ucan-lab/items/63d2a39914dc51b547ae
