name: Check Changes

on:
  workflow_call:
    outputs:
      lambda_changed:
        description: "Flag indicating if Lambda-related files changed"
        value: ${{ jobs.check-changes.outputs.lambda_changed }}
      backend_changed:
        description: "Flag indicating if backend-related files changed"
        value: ${{ jobs.check-changes.outputs.backend_changed }}
      frontend_changed:
        description: "Flag indicating if frontend-related files changed"
        value: ${{ jobs.check-changes.outputs.frontend_changed }}

jobs:
  check-changes:
    runs-on: ubuntu-22.04
    # 変更のチェックを行うジョブ
    outputs:
      lambda_changed: ${{ steps.filter.outputs.lambda_changed }}
      backend_changed: ${{ steps.filter.outputs.backend_changed }}
      frontend_changed: ${{ steps.filter.outputs.frontend_changed }}
    # リポジトリのコードをチェックアウト
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # パスのフィルターを適用することで、変更の有無を判定する
    - name: Check Paths
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          lambda_changed:
            - '.github/workflows/**'
            - '.github/workflows/deploy-lambda-and-migrate.yml'
            - 'db/migrations/**'
            - 'lambda/migrate/**'
          backend_changed:
            - '.github/workflows/**'
            - '.github/workflows/backend-ecs-build-and-deploy.yml'
            - 'backend/**'
          frontend_changed:
            - '.github/workflows/**'
            - '.github/workflows/frontend-ecs-build-and-deploy.yml'
            - 'frontend/**'
