# 共通設定ワークフローの定義
name: Common Configuration

# このワークフローが他のワークフローから呼び出されることを指定
on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
    secrets: inherit
    outputs:
      lambda_changed:
        description: "Whether lambda code has changed"
        value: ${{ jobs.check-changes.outputs.lambda_changed }}

# ジョブの定義
jobs:
  check-changes:
    runs-on: ubuntu-22.04
    outputs:
      lambda_changed: ${{ steps.filter.outputs.lambda_changed }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          lambda_changed:
            - 'db/migrations/**'
            - 'lambda/migrate/**'

  configure-aws:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.env_name }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.PROJECT }}-github-actions-role
          role-session-name: ${{ secrets.PROJECT }}-github-actions

  setup-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3