# Lambdaデプロイワークフローの定義
name: Deploy Lambda

# このワークフローが他のワークフローから呼び出されることを指定
on:
  workflow_call:

# 環境変数の設定
env:
  ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || startsWith(github.ref, 'refs/heads/feature/') && 'prod' || '' }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  PROJECT: ${{ secrets.PROJECT }}
  AWS_REGION: ap-northeast-1

# ジョブの定義
jobs:
  deploy-lambda:
    runs-on: ubuntu-22.04
    steps:
      # リポジトリのコードをチェックアウト
      - uses: actions/checkout@v4
      
      # AWS認証情報を設定
      - name: Configure AWS credentials
        uses: ./.github/workflows/common-config.yml
        with:
          job: configure-aws

      # Amazon ECRにログイン
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # LambdaコンテナイメージのビルドとプッシュAmazon ECRにプッシュ
      - name: Build and Push Lambda Container Image
        run: |
          docker build -t ${{ env.PROJECT }}-db-lambda-migrate:${{ github.sha }} -f lambda/migrate/Dockerfile .
          docker tag ${{ env.PROJECT }}-db-lambda-migrate:${{ github.sha }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.PROJECT }}-db-lambda-migrate-${{ env.ENV_VAR }}:${{ github.sha }}
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.PROJECT }}-db-lambda-migrate-${{ env.ENV_VAR }}:${{ github.sha }}

      # Lambda関数を更新
      - name: Update Lambda Function
        run: |
          aws lambda update-function-code --function-name ${{ env.PROJECT }}-db-migration-lambda-${{ env.ENV_VAR }} \
            --image-uri ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.PROJECT }}-db-lambda-migrate-${{ env.ENV_VAR }}:${{ github.sha }}

      # データベースマイグレーションを実行
      - name: Run Database Migration
        run: |
          aws lambda invoke --function-name ${{ env.PROJECT }}-db-migration-lambda-${{ env.ENV_VAR }} --payload '{}' response.json
          cat response.json
