# メインワークフローの定義
name: Main Workflow

# ワークフローのトリガー条件を設定
on:
  push:
    branches:
    - "develop"
    - "main"
    - "feature/**"
    paths:
      - '.github/workflows/**'
      - 'backend/**'
      - 'db/migrations/**'
      - 'lambda/migrate/**'

# 環境変数の設定
env:
  ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || startsWith(github.ref, 'refs/heads/feature/') && 'prod' || '' }}

# ジョブの定義
jobs:
  # 共通設定のジョブ
  common-config:
    uses: ./.github/workflows/common-config.yml
    secrets: inherit

  # Lambdaのデプロイを行うジョブ
  deploy-lambda:
    needs: common-config
    if: needs.common-config.outputs.lambda_changed == 'true'
    uses: ./.github/workflows/deploy-lambda.yml
    secrets: inherit

  # バックエンドのデプロイを行うジョブ
  deploy-backend:
    needs: [common-config, deploy-lambda]
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
