name: Main Workflow

on:
  push:
    branches:
    - "develop"
    - "main"
    - "feature/**"
    paths:
      - '.github/workflows/**'
      - 'backend/**'
      - 'db/migrations/**'
      - 'lambda/migrate/**'

jobs:
  common-config:
    uses: ./.github/workflows/common-config.yml
    with:
      env_name: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || startsWith(github.ref, 'refs/heads/feature/') && 'prod' || '' }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      PROJECT: ${{ secrets.PROJECT }}

  deploy-lambda:
    needs: common-config
    if: needs.common-config.outputs.lambda_changed == 'true'
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      env_name: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || startsWith(github.ref, 'refs/heads/feature/') && 'prod' || '' }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      PROJECT: ${{ secrets.PROJECT }}

  deploy-backend:
    needs: [common-config, deploy-lambda]
    uses: ./.github/workflows/deploy-backend.yml
    with:
      env_name: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || startsWith(github.ref, 'refs/heads/feature/') && 'prod' || '' }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      PROJECT: ${{ secrets.PROJECT }}