# メインワークフローの定義
name: Main Workflow

# ワークフローのトリガー条件を設定
on:
  push:
    branches:
    - "develop"
    - "main"
    - "feature/**"
    paths:
      - '.github/workflows/**'
      - 'backend/**'
      - 'db/migrations/**'
      - 'lambda/migrate/**'

# ジョブの定義
jobs:
  # 環境を設定するジョブ
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.env_name }}
    steps:
      - id: set-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
            echo "env_name=development" >> $GITHUB_OUTPUT
          else
            echo "env_name=development" >> $GITHUB_OUTPUT
          fi

  # 共通設定のジョブ
  common-config:
    needs: set-environment
    uses: ./.github/workflows/common-config.yml
    with:
      environment: ${{ needs.set-environment.outputs.env_name }}
    secrets: inherit

  # Lambdaのデプロイを行うジョブ
  deploy-lambda:
    needs: [set-environment, common-config]
    if: needs.common-config.outputs.lambda_changed == 'true'
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      environment: ${{ needs.set-environment.outputs.env_name }}
    secrets: inherit

  # バックエンドのデプロイを行うジョブ
  deploy-backend:
    needs: [set-environment, common-config, deploy-lambda]
    uses: ./.github/workflows/deploy-backend.yml
    with:
      environment: ${{ needs.set-environment.outputs.env_name }}
    secrets: inherit
